jobsboard/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from .views import *
from .views_candidates import *
from .views_employers import *
from .views_frontend import *
from django.contrib.auth.views import *
from .job_processor.processor import HttpCallback
from .stripe import *

from django.contrib.sitemaps.views import sitemap


urlpatterns = [
    
    path('403/', TemplateView.as_view(template_name='403.html')),
    path('404/', TemplateView.as_view(template_name='404.html')),
    path('408/', TemplateView.as_view(template_name='408.html')),
    path('500/', TemplateView.as_view(template_name='500.html')),

    path('update-data/', UpdateData.as_view(), name='update-data'),
    
    path('', Homepage.as_view(), name='home'),
    path('all/', Homepage.as_view(), name='all_jobs'),
    path('reject/', Homepage.as_view(), name='reject'),
    path('add/', Homepage.as_view(), name='add'),
    path('requested/', Homepage.as_view(), name='requested'),

    path('wx-endpoint/', HttpCallback.as_view()),

    path('job/<int:pk>/', JobDetailView.as_view(), name='job'),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': {'jobs': JobSitemap()}},
        name='django.contrib.sitemaps.views.sitemap',
    ),

    path('robots.txt', TemplateView.as_view(template_name='jobsboard/robots.txt', content_type='text/plain')),
    path("faq/", TemplateView.as_view(template_name='jobsboard/faqs/faqs.html'), name="faq"),
    path("about/", AboutView.as_view(), name="about"),
    path('contact/', ContactView.as_view(), name='contact'),
    path('message-sent/', MessageSentSuccess.as_view(), name='message-sent'),
    path('terms-and-conditions/', TemplateView.as_view(template_name='jobsboard/terms.html'), name='terms'),

    path('register/', Registration.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),

    # Activate account
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})/$',
    activate_account, name='activate'),
    path('account-activated/', TemplateView.as_view(template_name='registration/account_activated.html'), name='activated'),

    # Password Reset
    path('reset-password/', CustomPasswordResetView.as_view(), name ='reset_password'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name ='password_reset_done'),
    re_path(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})/$', CustomPasswordResetConfirmView.as_view(), name ='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name ='password_reset_complete'),
    path('password-updated/', TemplateView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),


    # Payments
    # path('pay/', CreateStripeCheckoutSessionView.as_view(), name='pay'),
    path('payment-successful/', SuccessfulPaymentView.as_view()),
    path('payment-cancelled/', TemplateView.as_view(template_name="jobsboard/stripe/cancel.html")),
    path("webhooks/stripe/", StripeWebhookView.as_view(), name="stripe-webhook"),


    # Shared backend URLs
    re_path(r'view-candidate/(?P<pk>\d+)?/?$', CandidateProfile.as_view(), name='view-candidate'),
    path('delete-profile-pic/', DeleteProfilePic.as_view()), #done
    path('update-app-status/', UpdateAppStatus.as_view(), name='update-status'),
    path('change-password/', ChangePasswordInProfile.as_view(), name ='change-password'),
    re_path(r'delete-job-app/(?P<pk>\d+)?$', DeleteJobApplication.as_view(), name='delete-job-app'),
    re_path(r'view-employer/(?P<pk>\d+)?/?$', ViewEmployerProfile.as_view(), name='view-employer'),


   

    # Candidate URLs
    path('get-wechat-id/', GetWechatID.as_view(), name='get-wechat'),
    path('edit-candidate-profile/', EditCandidateProfile.as_view(), name='edit-candidate'),
    path('edit-candidate-media/', EditCandidateMedia.as_view(), name='edit-candidate-media'),
    path('delete-cv/', DeleteCV.as_view(), name='delete-cv'), #done
    re_path(r'delete-media/(?P<media>([0-9]+/)+)?$', DeleteMedia.as_view(), name='delete-media'), #done
    path('handle-likes/', CreateDeleteLike.as_view(), name='create-delete-like'),
    path('favourite-jobs/', FavouriteJobs.as_view(), name='fav-jobs'),
    path('job-applications/', JobApplications.as_view(), name='job-apps'),





  # Employer URLs
    path('edit-employer-profile/', EditEmployerProfile.as_view(), name='edit-employer'), 
    path('post-job/', JobPostView.as_view(), name='post-job'),
    re_path(r'promote-job/(?P<pk>\d+)?/?$', PromoteJob.as_view(), name='promote-job'),
    path('manage-jobs/', ManageJobs.as_view(), name='manage-jobs'),
    path('edit-job/<int:pk>/', EditJobView.as_view(), name='edit-job'),
    re_path(r'delete-job/(?P<pk>\d+)?/?$', DeleteJob.as_view(), name='delete-job'), #not done
    path('view-applications/', ViewApplications.as_view(), name='employer-apps'),
    path('view-applications/<int:pk>/', ViewApplicantsForJob.as_view(), name='apps-by-job'),
   
]

jobsite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('tz_detect/', include('tz_detect.urls')),
    re_path(r'^fp/', include('django_drf_filepond.urls')),
    path("", include("jobsboard.urls")),
    path("admin/", admin.site.urls),    
]

jobsboard/forms.py
from django import forms
from .models import *
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm, 
UsernameField, PasswordResetForm, SetPasswordForm, PasswordChangeForm)
from django.contrib.auth.hashers import check_password
from django.contrib.auth import password_validation

from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError

from phonenumber_field.formfields import PhoneNumberField
from captcha.fields import CaptchaField, CaptchaTextInput

from datetime import date
import re
import requests
import json


wId = os.getenv('wId')


class SearchBox(forms.Form):
    search_terms = forms.CharField(label="Search", max_length=200,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search Job Descriptions'
    }))




# Customizes the HTML Select element
from django.forms import Select
class Select(Select):
    def create_option(self, *args,**kwargs):
        option = super().create_option(*args,**kwargs)
        if not option.get('value'):
            option['attrs']['disabled'] = 'disabled'
            option['attrs']['selected'] = 'selected'
        return option


# Dynamically get the available locations and job types
def get_option_list(qs, qtype):

    all_vals = []
    for q in qs:
        if qtype == 'cities':
            all_vals += q.cities
        elif qtype == 'types':
            all_vals += q.job_types
        elif qtype == 'subs':
            all_vals += q.subjects

    new_vals = []
    main_cities = ['beijing', 'guangzhou', 'shanghai', 'shenzhen']
    capital_subs = ['esl', 'ielts', 'toefl', 'toeic', 'p.e.']

    for x in sorted(set(all_vals)):
        if x not in main_cities:
            if ' ' in x:
                new_vals.append((x,x.title()))
            elif x in ['dj', 'ktv'] or x in capital_subs:
                # print(x)
                new_vals.append((x,x.upper()))
            else:
                new_vals.append((x,x.capitalize()))

    if qtype == 'cities':
        new_vals = [(c, c.capitalize()) for c in main_cities] + new_vals

    if qtype == 'cities':
        heading = 'Location'
    elif qtype == 'types':
        heading = 'Job Types'
    elif qtype == 'subs':
        heading = 'Subjects'

    return [(0, heading)] + new_vals




SEARCH_OPTIONS = (
    ('show_all', 'Show all results'),
    ('has_wechat', 'Only show adverts with Wechat IDs'),
    ('is_employer','Only show adverts from recruiters registered with this site'),
    ('no_wechat', 'Only show adverts without a Wechat ID'),
)


class SearchJobs(forms.Form):

# Pass the qs from the view to prevent further DB hits
    def __init__(self, qs, *args, **kwargs):
    
        super().__init__(*args, **kwargs)
        self.fields['type'].choices = get_option_list(qs, 'types')
        self.fields['loc'].choices = get_option_list(qs, 'cities')
        self.fields['sub'].choices = get_option_list(qs, 'subs')
        

    q = forms.CharField(max_length=200,
        required=False,
        widget=forms.TextInput(
            attrs={
            'placeholder': 'Search By Keyword',
            # "autofocus": True,
            "class": "form-control",
    }))

    type = forms.ChoiceField(
        required=False,
        widget=Select(attrs={"class": "form-select"})
    )

    loc = forms.ChoiceField(
        required=False,
        widget=Select(attrs={"class": "form-select"})
    )

    sub = forms.ChoiceField(
        required=False,
        widget=Select(attrs={"class": "form-select"})
    )

    options = forms.ChoiceField(
        initial='show_all',
        widget=forms.RadioSelect(attrs={'form':'search-form'}),
        choices=SEARCH_OPTIONS,
    )

    posters = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'form':'search-form', 'class':'autocomplete', })
    )

    



class LoginForm(AuthenticationForm):
    
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            # "placeholder": "Username",
            # "class": "form-control"
        }))
    
    # email = forms.EmailField()
    
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            # "placeholder": "Password",
            # "class": "form-control"  
        }))

    error_messages = {
        "invalid_login": _('''
            <h5 class="text-danger">
            Please enter a valid Username and/or Password. Note that the password field is case-sensitive.</h5>        
        '''),

        "inactive": _('''
        <h2 class="text-center text-danger mb-2">This account is inactive!</h2> 
        <h5 class="text-danger">If this is your first time to log in, 
        then make sure you have activated the account with the email we sent you.</h5>
        '''),
    }

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean_username(self):
        return self.cleaned_data['username'].lower()






class SiteUserMixin:
    
    def clean_wechat_id(self):
        wechat_id = self.cleaned_data['wechat_id'] or None

        if wechat_id:
            wechat_id = wechat_id.strip()
            print(f"Wechat ID: {wechat_id}")

        # Check if it exists (sign up) and same as before
            if hasattr(self,'old_wechat_id') and wechat_id == self.old_wechat_id:
                    return wechat_id 
        # Check if already registered
            if SiteUser.objects.filter(wechat_id=wechat_id).exists():
                raise ValidationError(
                    mark_safe(_('Someone else has already registered this Wechat ID. Pick another one.'))
                    )
        
        return wechat_id
    
    # Then check if it even exists
    #     headers = {
    #         'Authorization': 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMzE2MzI3MzY3NyIsInBhc3N3b3JkIjoiJDJhJDEwJHlUamdScXFNQnJvb3VWbGk2Y1hvc2VoL3V1cnVOSnYuWnU4Mjh1aDBJZWM0cDFrVHMwZENDIn0.3m2bDjrQzDJkV8poSZHakWgmt3zMKdeb1NX_hTrhDs5p0TWnpHZA5BiVj43rSZZ4z8AtkXyqgZCHAXoirKi8fw',
    #         'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
    #         'Content-Type': 'application/json'
    #     }

    #     payload = {
    #         'wId' : wId,
    #         'wcId' : wechat_id
    #     }

    #     # Check for code 1000 otherwise throw error
    #     # https://wkteam.cn/api-wen-dang2/hao-you-cao-zuo/serchUser.html

    #     data = {}
        
    #     try:
    #         res = requests.post('http://59.36.146.193:9899/searchUser',headers=headers,data=json.dumps(payload))
    #         data = json.loads(res.text)['data']
    #         print(f'DATA: {data}')
    #     except Exception as e:
    #         print(e)

    # # Check if it errored. Won't work inside try block
    #     if 'errMsg' in data:
    #         raise ValidationError(
    #             mark_safe(_("Whoooa partner, can't seem to find that Wechat ID. Did you make a mistake?"))
    #             )

        return wechat_id




USER_TYPE = (
    ('candidate', 'Candidate 求职者'),
    ('employer', 'Employer 猎头雇佣的')
)

SEX = (
    ('male', 'male'),
    ('female', 'female')
)


class SignUpForm(UserCreationForm,SiteUserMixin):

    terms = forms.BooleanField(required=True)
    # wechat = forms.CharField(required=False)

    user_type = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=USER_TYPE,
        error_messages={'required': 'You must choose your User Type.'}
    )

    sex = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=SEX,
    )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            print(f'FIELD: {field}')
            if field not in ('user_type', 'sex', 'country'):
                self.fields[field].widget.attrs['class'] = 'form-control'

        # self.fields['user_type'].empty_label = None
        # self.fields['user_type'].widget.attrs['class'] = 'form-select'
        self.fields['terms'].widget.attrs['class'] = 'select-box'
        self.fields['username'].widget.attrs['autofocus'] = False
        self.fields['country'].widget.attrs['class'] = 'form-select form-control'
        # self.fields['country'].initial = ''

    class Meta(UserCreationForm.Meta):
        model = SiteUser
        fields = UserCreationForm.Meta.fields + ('first_name', 'email', 'wechat_id', 'country')


    def clean_sex(self):
        sex = self.cleaned_data['sex']

    # Only clean this if there's a user_type
        if 'user_type' in self.cleaned_data:
            user_type = self.cleaned_data['user_type']
        else:
            return sex

        if user_type == 'candidate' and not sex:
            self.fields['sex']
            raise ValidationError(
                    mark_safe(_(f'You must select a Gender.'))
                )
        return sex
    

    def clean_username(self):
        return self.cleaned_data['username'].lower()







JOB_TYPES = [
    ('teacher', 'Teacher 老师'),
    ('online teacher', 'Online Teacher 在线老师'),
    ('model','Model 模特'),
    ('actor','Actor 演员'),
    ('voiceover','Voiceover 配音'),
    ('recording','Recording 录音'),
    ('tiktok','Tiktok 抖音'),
    ('translator','Translator 翻译'),
    ('bar work','Bar Work 酒吧'),
    ('singer','Singer 歌手'),
    ('musician','Musician 音乐家'),
    ('dancer','Dancer 舞蹈'),
    ('ktv','KTV'),
    ('travel companion', 'Travel Companion 伴游'),
    ('other', 'Other 其他'),
]



class JobFormMixin(forms.ModelForm):

    start_date = forms.DateField(required=False, 
        widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    job_types = forms.MultipleChoiceField(

jobsboard/templates/jobsboard/employers/edit-employer-profile.html
{% extends "../layouts/employer-base.html" %}
{% load static %}

{% block title %} Edit Employer Profile {% endblock %}

{% block stylesheets %}

<style>
    .form-control:disabled {
        background-color: #e9ecef !important;
    }

    #id_job_types {
        display: grid;
        grid-template-columns:repeat(auto-fit,minmax(200px, 1fr));
        row-gap: 10px;
    }

    @media (max-width: 550px) {
        #id_job_types {
        grid-template-columns:repeat(auto-fit,minmax(170px, 1fr));
        row-gap: 5px;
        }
    }

    input[type=checkbox] {
        transform: scale(1.2);
    }

    .form-label {
        font-size: 1rem !important;
    }

    .errorlist {
        font-size: 1.2rem;
    }


    #profile-image {
        margin-top: 10%;
        height: auto;
        width: 80%;
        clip-path: circle();
    }

    #profile-image-input {
        padding: 6%;
    }

    .cropper-view-box {
        border-radius: 60%;
    }
    .cropper-face {
        background-color:inherit !important;
    }

    .cropper-buttons {
        position: absolute;
        left: 10px;
        width: 70px;
        z-index: 9999;
        font-size: 40px;
        color: white;
        background-color: green;
    }

</style>

<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet" />
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/filepond-plugin-media-preview@1.0.11/dist/filepond-plugin-media-preview.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.css" integrity="sha512-087vysR/jM0N5cp13Vlp+ZF9wx6tKbvJLwPO8Iit6J7R+n7uIMMjg37dEgexOshDmDITHYY5useeSmfD1MYiQA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock stylesheets %}

{% block innercontent %}


<div class="pxp-dashboard-content-details">

    
{% if messages %}
    {% for message in messages %}
        
        {% if message.tags == 'success' %}
        <div class="alert alert-success subs-removed-success" role="alert">
            {{ message }}
        </div>
        {% endif %}

        {% if message.tags == 'info' %}
        <div class="alert alert-info subs-remove-info" role="alert">
            {{ message }}
        </div>
        {% endif %}

        {% if message.tags == 'error' %}
        <div class="alert alert-danger subs-removed-error" role="alert">
            {{ message }}
        </div>
        {% endif %}

    {% endfor %}
{% endif %}

    <h1>Edit Profile</h1>
    <p class="pxp-text-light">Edit your employer profile page info.</p>

    <form method="post" enctype="multipart/form-data" id="employer-profile-form">

        {% csrf_token %}

        <div class="row">
            <h4>Edit your profile pic</h4>
            <div class="col-sm-6" id="profile-image-input">                        
                <input type="file" class="pond" id="profile-image-uploader" name="profile_pic" />
            </div>

            <div class="col-sm-6" id="profile-pic-container">
                <div class="text-center">
                    
                    <img src="
                    {% if request.user.profile_pic %}
                    {{ request.user.profile_pic.url }}
                    {% endif %}
                    "
                    id="profile-image" alt="profile picture">
                    
                </div>
                <div class="text-center">
                    <button type="button" id="delete-profile-pic-btn" class="mt-3 btn btn-danger">Delete Profile Pic</button>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-name" class="form-label">Employer / Recruiter Name</label>
                    {{ form.name }}
                </div>
            </div>

            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-email" class="form-label">Email</label>
                    {{ form.email }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-phone" class="form-label">Whatsapp</label>
                    {{ form.phone_number }}
                </div>
                <span class="text-danger">{{ form.phone_number.errors }}</span>
            </div>
            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-wechat" class="form-label">Wechat ID</label>
                    {{ form.wechat_id }}
                </div>
                <span class="text-danger">{{ form.wechat_id.errors }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="pxp-employer-city" class="form-label">City</label>
                    {{ form.city }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="pxp-employer-country" class="form-label">Country</label>
                        {{ form.country }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-website" class="form-label">Website</label>
                        {{ form.website }}
                </div>
                <span class="text-danger">{{ form.website.errors }}</span>
            </div>
            <div class="col-sm-6">
                <div class="mb-3">
                    <label for="pxp-employer-size" class="form-label">Company Size</label>
                    {{ form.company_size }}
                </div>
            </div>
        </div>
        


        <div class="mb-3">
            <label for="pxp-employer-job-types" class="form-label">Which Types of Jobs Do You Recruit For?</label>
            
            {{ form.job_types }}

        </div>


        <div class="mb-3">
            <label for="pxp-employer-about" class="form-label">Tell Potential Candidates Something About You</label>
            {{ form.intro }}
        </div>


        <div class="mt-4 mt-lg-5">
            <button type="submit" class="btn rounded-pill pxp-secondary-cta upload-btn">Save Profile</button>
        </div>
    </form>
</div>

{% endblock innercontent %}



{% block javascript %}
<script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>

<script src="https://unpkg.com/filepond-plugin-image-edit/dist/filepond-plugin-image-edit.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>

<script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js" integrity="sha512-JyCZjCOZoyeQZSd5+YEAcFgz2fowJ1F1hyJOXgtKu4llIa0KneLcidn5bwfutiehUTiOuK87A986BZJMko0eWQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/cropper.js' %}"></script>


<script>

$(document).ready(function() {
    if($('.alert')){
        $('.alert').fadeTo(5000, 500).slideUp(500)
    }
})


FilePond.registerPlugin(

    FilePondPluginImageEdit,
    FilePondPluginImagePreview,
    FilePondPluginFileValidateType,
    FilePondPluginFileValidateSize,
    FilePondPluginImageTransform,

);



const profileImg = FilePond.create(
  document.querySelector('#profile-image-uploader'),{
    labelIdle: `Drag & Drop your profile pic or <span class="filepond--label-action">Browse</span>`,
    imagePreviewHeight: 170,
    stylePanelLayout: 'compact circle',
    styleLoadIndicatorPosition: 'center bottom',
    styleProgressIndicatorPosition: 'right bottom',
    styleButtonRemoveItemPosition: 'left bottom',
    styleButtonProcessItemPosition: 'right bottom',
    credits: false,
    imageEditEditor: editor,

// Error messages not shown for compact circles so just blocked them from adding it
// Can be updated later
    dropValidation: true,
    maxFileSize: '20MB', //Resized post submission anyway
    acceptedFileTypes: ['image/*'],
    fileValidateTypeLabelExpectedTypes: 'Should be an image file like .jpg, .png',

    onaddfile: function(error, file) {
        console.log('File added: [' + error + ']   file: [' + file.id + ']');
        $('.upload-btn').attr('disabled','');
    },

    onprocessfile: function(error, file) {
        console.log('On Process Fired')
        $('.upload-btn').removeAttr('disabled');
  
    },

   



    server: {

        url: '/fp',
        patch: '/patch/',
        revert: '/revert/',
        fetch: '/fetch/?target=',
        load: '/load/',
        restore: '/restore/',

        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        },


        process: {
                url: '/process/',
                method: 'POST',
                headers: {
                'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val()
                },
                withCredentials: false,
                ondata: (formData) => {  
                    
                    var upload_field = '';
                    
                    for (var item of formData.keys()) {
                        console.log(item)
                        upload_field = item;
                        break;
                    }
                    if (upload_field !== '') {
                        formData.append('fp_upload_field',upload_field);
                    }
                    return formData;
                },
            }
        }
})


$(document).ready(()=> {
    if(location.href === $('#profile-image')[0].src){
        $('#profile-pic-container').hide()
    }
})


let profile_pic_removed = false

document.querySelector('#employer-profile-form').addEventListener('formdata', e => {
        //e.preventDefault()
        console.log(e)
        console.log('Removed sent')
        e.formData.set('profile_pic_removed',profile_pic_removed);
        
    
});
    



$('#delete-profile-pic-btn').on('click', () => {
    //Restore generic images
    $('#profile-pic-container').hide()
    $('.pxp-dashboard-side-user-nav-avatar')[0].style.backgroundImage = 'url("{% static 'images/wechat-registered.webp' %}")'
    $('.pxp-user-nav-avatar')[0].style.backgroundImage = 'url("{% static 'images/wechat-registered.webp' %}")'
    profile_pic_removed = true

    $.ajax({
        type: 'DELETE',
        url: '/delete-profile-pic/',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
        },
        dataType: 'html'
    })
})

</script>
{% endblock javascript %}