jobsboard/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from .views import *
from .views_candidates import *
from .views_employers import *
from .views_frontend import *
from django.contrib.auth.views import *
from .job_processor.processor import HttpCallback
from .stripe import *

from django.contrib.sitemaps.views import sitemap


urlpatterns = [
    
    path('403/', TemplateView.as_view(template_name='403.html')),
    path('404/', TemplateView.as_view(template_name='404.html')),
    path('408/', TemplateView.as_view(template_name='408.html')),
    path('500/', TemplateView.as_view(template_name='500.html')),

    path('update-data/', UpdateData.as_view(), name='update-data'),
    
    path('', Homepage.as_view(), name='home'),
    path('all/', Homepage.as_view(), name='all_jobs'),
    path('reject/', Homepage.as_view(), name='reject'),
    path('add/', Homepage.as_view(), name='add'),
    path('requested/', Homepage.as_view(), name='requested'),

    path('wx-endpoint/', HttpCallback.as_view()),

    path('job/<int:pk>/', JobDetailView.as_view(), name='job'),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': {'jobs': JobSitemap()}},
        name='django.contrib.sitemaps.views.sitemap',
    ),

    path('robots.txt', TemplateView.as_view(template_name='jobsboard/robots.txt', content_type='text/plain')),
    path("faq/", TemplateView.as_view(template_name='jobsboard/faqs/faqs.html'), name="faq"),
    path("about/", AboutView.as_view(), name="about"),
    path('contact/', ContactView.as_view(), name='contact'),
    path('message-sent/', MessageSentSuccess.as_view(), name='message-sent'),
    path('terms-and-conditions/', TemplateView.as_view(template_name='jobsboard/terms.html'), name='terms'),

    path('register/', Registration.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),

    # Activate account
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})/$',
    activate_account, name='activate'),
    path('account-activated/', TemplateView.as_view(template_name='registration/account_activated.html'), name='activated'),

    # Password Reset
    path('reset-password/', CustomPasswordResetView.as_view(), name ='reset_password'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name ='password_reset_done'),
    re_path(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,50})/$', CustomPasswordResetConfirmView.as_view(), name ='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name ='password_reset_complete'),
    path('password-updated/', TemplateView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),


    # Payments
    # path('pay/', CreateStripeCheckoutSessionView.as_view(), name='pay'),
    path('payment-successful/', SuccessfulPaymentView.as_view()),
    path('payment-cancelled/', TemplateView.as_view(template_name="jobsboard/stripe/cancel.html")),
    path("webhooks/stripe/", StripeWebhookView.as_view(), name="stripe-webhook"),


    # Shared backend URLs
    re_path(r'view-candidate/(?P<pk>\d+)?/?$', CandidateProfile.as_view(), name='view-candidate'),
    path('delete-profile-pic/', DeleteProfilePic.as_view()), #done
    path('update-app-status/', UpdateAppStatus.as_view(), name='update-status'),
    path('change-password/', ChangePasswordInProfile.as_view(), name ='change-password'),
    re_path(r'delete-job-app/(?P<pk>\d+)?$', DeleteJobApplication.as_view(), name='delete-job-app'),
    re_path(r'view-employer/(?P<pk>\d+)?/?$', ViewEmployerProfile.as_view(), name='view-employer'),


   

    # Candidate URLs
    path('get-wechat-id/', GetWechatID.as_view(), name='get-wechat'),
    path('edit-candidate-profile/', EditCandidateProfile.as_view(), name='edit-candidate'),
    path('edit-candidate-media/', EditCandidateMedia.as_view(), name='edit-candidate-media'),
    path('delete-cv/', DeleteCV.as_view(), name='delete-cv'), #done
    re_path(r'delete-media/(?P<media>([0-9]+/)+)?$', DeleteMedia.as_view(), name='delete-media'), #done
    path('handle-likes/', CreateDeleteLike.as_view(), name='create-delete-like'),
    path('favourite-jobs/', FavouriteJobs.as_view(), name='fav-jobs'),
    path('job-applications/', JobApplications.as_view(), name='job-apps'),





  # Employer URLs
    path('edit-employer-profile/', EditEmployerProfile.as_view(), name='edit-employer'), 
    path('post-job/', JobPostView.as_view(), name='post-job'),
    re_path(r'promote-job/(?P<pk>\d+)?/?$', PromoteJob.as_view(), name='promote-job'),
    path('manage-jobs/', ManageJobs.as_view(), name='manage-jobs'),
    path('edit-job/<int:pk>/', EditJobView.as_view(), name='edit-job'),
    re_path(r'delete-job/(?P<pk>\d+)?/?$', DeleteJob.as_view(), name='delete-job'), #not done
    path('view-applications/', ViewApplications.as_view(), name='employer-apps'),
    path('view-applications/<int:pk>/', ViewApplicantsForJob.as_view(), name='apps-by-job'),
   
]

jobsite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('tz_detect/', include('tz_detect.urls')),
    re_path(r'^fp/', include('django_drf_filepond.urls')),
    path("", include("jobsboard.urls")),
    path("admin/", admin.site.urls),    
]

jobsboard/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
import os


NUM_EMPLOYEES = (
    (5,'Less Than 5'),
    (10,'6-10'),
    (20,'11-20'),
    (50,'21-50'),
    (100,'51-100'),
    (200,'101-200'),
    (500,'201-500'),
    (1000,'More Than 500')
)



# Cut down DB hits by fetching candidates and employers
class CustomUserManager(UserManager):
    def get(self, *args, **kwargs):
        return super().select_related('candidate','employer').get(*args, **kwargs)
       


class SiteUser(AbstractUser):
    first_name = models.CharField(_("first name"), max_length=150, blank=False)
    # last_name = models.CharField(_("last name"), max_length=150, blank=False)
    email = models.EmailField(_("email address"), unique=True, validators=[EmailValidator()], error_messages={
            'unique': _('That email address has already been registered. Please use another one.'),
        })
    
    wechat_id = models.CharField(blank=True, null=True)
    phone_number = PhoneNumberField(blank=True)
    city = models.CharField(blank=True)
    country = CountryField(blank=True)
    intro = models.TextField(blank=True)
    job_types = ArrayField(models.CharField(max_length=50), blank=True, null=True)
    profile_pic = models.ImageField(upload_to='images',null=True, blank=True)

    objects = CustomUserManager()
    
    class Meta:
        verbose_name = 'All User'



# Add type of agent - modelling, teacher etc
class Employer(models.Model):
    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE, related_name='employer')
    website = models.CharField(blank=True)
    company_size = models.CharField(max_length=6, choices=NUM_EMPLOYEES, default=5)
    
    def __str__(self):
        return self.user.first_name
    


class Candidate(models.Model):
    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE, related_name='candidate')
    sex = models.BooleanField(null=True)
    dob = models.DateField(max_length=8, blank=True, null=True)
    cv = models.FileField(upload_to='cvs', null=True, blank=True)
    cover_letter = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.user.first_name
    
    def cv_fname(self):
        return os.path.basename(self.cv.name)






# No need to validate as everything is converted to a webp
class CandidateImage(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='images')
    thumbnail = models.ImageField(upload_to='images', blank=True, null=True)


class CandidateVideo(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='videos')
    video = models.FileField(upload_to='videos')
    # ,validators=[FileExtensionValidator(allowed_extensions=['mp4','webm'])] - doesn't work
    thumbnail = models.CharField()

    def extension(self):
        name, extension = os.path.splitext(self.video.name)
        return 'video/' + extension[1:]



# Database to store wxid and wx_alias pairs
class WxidAlias(models.Model):
    wxid = models.CharField(max_length=50, unique=True)
    wx_alias = ArrayField(models.CharField(max_length=100), null=True, blank=True, default=list) #Make this so it only contains unique items with validator
    wx_alias_request_by_user = models.ForeignKey(Candidate, on_delete=models.CASCADE, blank=True, null=True)
    # List of timestamps of when each request was sent
    wx_alias_requests_sent_by_me = ArrayField(models.DateTimeField(), null=True, blank=True, default=list)
    notes = models.TextField()

    def __str__(self):
        return self.wxid

    class Meta:
        verbose_name = 'WXID Aliase'

    


class GroupId(models.Model):
    group_id = models.CharField(max_length=50, unique=True)
    group_name = models.CharField(max_length=50)
    wxids = models.ManyToManyField(WxidAlias, through='Handle')

    def __str__(self):
        return self.group_name


class Handle(models.Model):
    wxid = models.ForeignKey(WxidAlias, on_delete=models.CASCADE, related_name='handle')
    group = models.ForeignKey(GroupId, on_delete=models.CASCADE, related_name='handle')
    handle = models.CharField(max_length=50)

    def __str__(self):
        return str(self.handle)



YEARS_EXPERIENCE = [
    (None, 'Enter a period of time 输入经验时间'),
    ('0', 'No experience 无经验'),
    ('6','At least 6 months 至少6个月'),
    ('12','At least 1 year 至少一年'),
    ('24','At least 2 years 至少两年'),
    ('36','At least 3 years 至少三年'),
    ('60','At least 5 years 至少五年'),
    ('120','At least 10 years 至少十年'),
    ('121','More than 10 years 多于十年'),
]

EMPLOYMENT_TYPE = [
    (None, 'Enter an employment type 输入工作种类'),
    ('full', 'Full Time 全职'),
    ('part', 'Part Time 兼职'),
    ('remote', 'Remote  远程'),
    ('intern', 'Internship 实习生'),
    ('contract', 'Contract 合同'),
    ('training', 'Training 培训')
]

ACCOMMODATION = [
    (None, 'Enter accomodation type 输入住房种类'),
    ('shared', 'Shared Flat 合租'), 
    ('independent', 'Independent Flat 独立'),
    ('allowance', 'Housing Allowance 住房补贴'),
    ('none', 'None Provided 无')
]

CONTRACT_LENGTH = [
    (None, 'Enter contract length 输入合同期限'),
    ('one_off', 'One Off 一次性'), 
    ('1_day', '1 Day 一天'),
    ('1_week', '1 Week 一周'),
    ('1_month', '1 Month 一月'),
    ('3_months', '3 Months 三月'),
    ('6_months', '6 Months 六月'),
    ('1_year', '1 Year 一年'),
    ('2_years', '2 Years 两年'),
    ('5_years', '5 Years 五年'),
    ('on-going', 'On-going 不限日期')
]

PAY_SETTLEMENT_DATE = [
    (None, 'Enter when they will get paid 输入什么时候发工资'),
    ('same_day', 'Same Day 当天'),
    ('after_job_completion', 'After Job Completion 完成工作'),
    ('weekly', 'Weekly 每周性'),
    ('monthly', 'Monthly 每月性')
]


# Need to use a callable for some reason
def empty_list():
    return []

# Need to comment out path("", include("jobsboard.urls")), in urls to makemigrations for new fields
class Job(models.Model):
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now_add=True)
    is_draft = models.BooleanField(default=False)
# All messages are saved for review purposes.
# This is whether the parser can figure out whether it's an actual job
    is_job = models.BooleanField(default=True)
    scraped = models.BooleanField(default=True)

# If it is put through manually, then will be "owned" by an employer
    wx_handle = models.ForeignKey(Handle, on_delete=models.CASCADE, blank=True, null=True)
    wxid_alias = models.ForeignKey(WxidAlias, on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(GroupId, on_delete=models.CASCADE, blank=True, null=True)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, blank=True, null=True)

    cities = ArrayField(models.CharField(max_length=100), null=True, blank=True)
    job_types = ArrayField(models.CharField(max_length=100), null=True, blank=True, default=empty_list)
    subjects = ArrayField(models.CharField(max_length=100), null=True, blank=True, default=empty_list)
    job_description = models.TextField(unique=True, error_messages={
        'unique': _('A job with this job description already exists. Please do not copy and paste job descriptions across jobs.')
    })
    jd_translation = models.TextField(default='')
    job_title = models.CharField(max_length=200, null=True, blank=True)
    experience = models.CharField(choices=YEARS_EXPERIENCE, null=True, blank=True)
    employment_type = models.CharField(choices=EMPLOYMENT_TYPE, null=True, blank=True)
    salary_lower_range = models.PositiveIntegerField(null=True, blank=True)
    salary_upper_range = models.PositiveIntegerField(null=True, blank=True)

    accommodation = models.CharField(choices=ACCOMMODATION, null=True, blank=True)
    start_date = models.DateField(max_length=8, blank=True, null=True)
    contract_length = models.CharField(choices=CONTRACT_LENGTH, null=True, blank=True)
    pay_settlement_date = models.CharField(choices=PAY_SETTLEMENT_DATE, null=True, blank=True)
    
    class Meta:
        verbose_name_plural = "Jobs"

    def __str__(self):
        return self.job_description[:20]
    
    def get_absolute_url(self):
        return f'/job/{self.id}/'
    



class FavouriteJob(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='favourites')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='favourites')

    class Meta:
        constraints = [
        models.UniqueConstraint(fields=['candidate', 'job'], name='unique_favs')
    ]


STATUS = [
    ('pending', 'Pending'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
    ('revoked', 'Revoked'),
]

class JobApplication(models.Model):
    time_created = models.DateTimeField(auto_now_add=True)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='applications')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applications')
    status = models.CharField(choices=STATUS, default='pending')
    employer_removed = models.BooleanField(default=False)
    candidate_removed = models.BooleanField(default=False)

    class Meta:
        constraints = [
        models.UniqueConstraint(fields=['candidate', 'job'], name='unique_apps')
    ]
        
# Always starts with Pending

# Employer status
# Candidate revokes, candidate deletes => Revoked
# Employer approves, candidate deletes => Revoked
# Candidate revokes => Revoked

# Employer rejects, candidate deletes => Rejected
# Employer rejects => Rejected

# Employer approves => Approved

# Candidate status
# Candidate revokes, employer deletes => Revoked
# Candidate revokes => Revoked

jobsboard/templates/jobsboard/candidates/edit-candidate-profile.html
{% extends "../layouts/candidate-base.html" %}
{% load static %}

{% block title %} Edit Candidate Profile {% endblock %}

{% block stylesheets %}

<style>
    .form-control:disabled {
        background-color: #e9ecef !important;
    }

    #id_job_types {
        display: grid;
        grid-template-columns:repeat(auto-fit,minmax(200px, 1fr));
        row-gap: 10px;
    }

    @media (max-width: 550px) {
        #id_job_types {
        grid-template-columns:repeat(auto-fit,minmax(170px, 1fr));
        row-gap: 5px;
        }
    }

    input[type=checkbox] {
        transform: scale(1.2);
    }

    .form-label {
        font-size: 1.2rem !important;
    }

    .errorlist {
        font-size: 1.2rem;
    }


    #trash-can {
        display: block;
        color: red;
        font-size: 1.9rem;
        margin-right: 5px;
        cursor: pointer;
    }

    #trash-can:hover {
        opacity: 0.5;
    }

    #trash-can + a {
        font-size: 1.3rem;
    }


    .form-select, .form-control {
        font-size: 1.2rem;
    }

/* Prevent the whatsapp text from disappearing */
    @media (min-width:992px) and (max-width:1162px)  {
        #id_phone_number {
            font-size: 0.9rem;
        }
    }

    @media (min-width:575px) and (max-width:820px)  {
        #id_phone_number {
            font-size: 0.9rem;
        }
    }

    #id_cv{
        padding-left: 30px;
    }


    {% if cv_url %}
    #upload-cv { 
        display: none; 
    }
    {% endif %}

</style>

{% endblock stylesheets %}

{% block innercontent %}

<div class="pxp-dashboard-content-details">

{% if messages %}
    {% for message in messages %}
        
        {% if message.tags == 'success' %}
        <div class="alert alert-success subs-removed-success" role="alert">
            {{ message }}
        </div>
        {% endif %}

        {% if message.tags == 'info' %}
        <div class="alert alert-info subs-remove-info" role="alert">
            {{ message }}
        </div>
        {% endif %}

        {% if message.tags == 'error' %}
        <div class="alert alert-danger subs-removed-error" role="alert">
            {{ message }}
        </div>
        {% endif %}

    {% endfor %}
{% endif %}


    <h1>Edit Profile</h1>
    <p class="pxp-text-light">Edit your candidate profile page info.</p>

    <form method="post" enctype="multipart/form-data" id="candidate-form">

        {% csrf_token %}

        <div class="row mt-4 mt-lg-5">

            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-name" class="form-label">Name</label>
                        {{ form.name }}

                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-email" class="form-label">Email</label>
                        {{ form.email }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-dob" class="form-label">Date of Birth</label>
                        {{ form.dob }}
                    </div>
                    <span class="text-danger">{{ form.dob.errors }}</span>
                </div>

                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-name" class="form-label">Wechat ID</label>
                        {{ form.wechat_id }}
                    </div>
                    <span class="text-danger">{{ form.wechat_id.errors }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-sex" class="form-label">Sex</label>
                        {{ form.sex }}
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-name" class="form-label">WhatsApp</label>
                        {{ form.phone_number }}
                    </div>
                    <span class="text-danger">{{ form.phone_number.errors }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-location" class="form-label">Current City</label>
                        {{ form.city }}
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="pxp-candidate-candidate" class="form-label">Country of Origin</label>
                        {{ form.country }}
                    </div>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label for="pxp-candidate-job-types" class="form-label">Which Jobs Are You Most Interested In?</label>
            {{ form.job_types }}
        </div>

        <div class="mt-3 mb-3">
            <label for="pxp-candidate-about" class="form-label">About you</label>
            {{ form.intro }}
        </div>
            
        <div class="mt-4">

            {% if cv_url %}

            <div id="delete-cv">
                <h4>Your Uploaded CV</h4>
                <div class="d-flex">
                    <i id="trash-can" class="fa fa-trash me-2" aria-hidden="true" data-toggle="tooltip" 
                    title="Delete this CV"></i>
                    <a href="{{ cv_url }}">{{ cv_fname }}</a>
                </div>
               
            </div>
            
            {% endif %} 
            
          {# Has to be hidden and not else'd as may still need it #}  
            <div id="upload-cv">
                <h5 style="color:red;">You still haven't uploaded a CV.</h5>
                <label for="pxp-candidate-cv" class="form-label">Upload Your CV</label>
                {{ form.cv }}
            </div>
            <span class="text-danger">{{ form.cv.errors }}</span>
            
            
        </div>

        <div class="mt-4 mt-lg-5">
            <button type="submit" class="btn rounded-pill pxp-section-cta">Save Profile</button>
        </div>
    </form>
</div>

{% endblock innercontent %}

{% block javascript %}
<script>

$(document).ready(() =>{
    $('[data-toggle="tooltip"]').tooltip()
    $('.alert').fadeTo(5000, 500).slideUp(500)
});



//Get the filename when the page loads
//When the form is submitted, check the initial filename with the submitted filename
//This is a trivial check, so no need to store the val locally
let initialVal;

$(document).ready(()=> {
    initialVal = $('#delete-cv').find('a').text()
})

document.querySelector('#candidate-form').addEventListener('formdata', e => {
    cvHasChanged = $('#delete-cv').find('a').text() !== initialVal ? 1 : 0
    e.formData.set('cv_changed', cvHasChanged);
});


$('#trash-can').on('click', function(e) {
    e.preventDefault()

    $('#delete-cv').fadeOut(500, function() {
        $('#upload-cv').css('display', 'block')
    });

    $.ajax({
            type: 'DELETE',
            url: '/delete-cv/',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            dataType: 'html',
        });

    if(this.dataset.type !== 'cv'){
        this.parentNode.remove()
    }
})

</script>
{% endblock javascript %}